---
# - name: "install packages"
#   apt:
#     name: "*"
#     update_cache: yes
#     cache_valid_time: 3600

# - name: "install packages"
#   apt:
#     name:
#       - "{{ item }}"
#     state: latest
#   loop: "{{ packages }}"

- name: "install packages"
  ansible.builtin.apt:
    name:
      - nfs-common
      - unzip
    update_cache: yes
    cache_valid_time: 3600
    state: latest

- name: Get current AZ from AWS
  ansible.builtin.uri:
    url: http://169.254.169.254/latest/meta-data/placement/availability-zone
    return_content: yes
  register: aws_current_az

- name: Mount an NFS volume
  ansible.posix.mount:
    src: "{{ aws_current_az.content }}.fs-06f3877b4904a4194.efs.eu-west-2.amazonaws.com"
    path: /opt/ipc/home
    opts: nfsvers=4.1
    state: mounted
    fstype: nfs4

- name: Ensure group "infrastructure" exists
  ansible.builtin.group:
    name: infrastructure
    state: present
    gid: 1100
     
- name: Ensure group "support" exists
  ansible.builtin.group:
    name: support
    state: present
    gid: 1200

- name: Ensure group "developers" exists
  ansible.builtin.group:
    name: developers
    state: present
    gid: 1300

- name: Ensure group "networks" exists
  ansible.builtin.group:
    name: networks
    state: present
    gid: 1400

# - name: Add the user 'woronowl'
#   ansible.builtin.user:
#     name: woronowl
#     shell: /bin/bash
#     groups: infrastructure
#     append: yes
#     create_home: yes
#     uid: 1101
#     group: 1101
#     home: /opt/ipc/home/woronowl

# - name: Set authorized keys taken from url
#   ansible.posix.authorized_key:
#     user: charlie
#     state: present
#     key: https://github.com/seag-rvc.keys