---
# - name: "install packages"
#   apt:
#     name: "*"
#     update_cache: yes
#     cache_valid_time: 3600

# - name: "install packages"
#   apt:
#     name:
#       - "{{ item }}"
#     state: latest
#   loop: "{{ packages }}"

- name: "install packages"
  ansible.builtin.apt:
    name:
      - nfs-common
      - unzip
    update_cache: yes
    cache_valid_time: 3600
    state: latest

- name: Get current AZ from AWS
  uri:
    url: http://169.254.169.254/latest/meta-data/placement/availability-zone
    return_content: yes
  register: aws_current_az

- name: Mount an NFS volume
  ansible.posix.mount:
    src: "{{ aws_current_az.content }}.fs-06f3877b4904a4194.efs.eu-west-2.amazonaws.com"
    path: /opt/ipc/home
    opts: nfsvers=4.1
    state: mounted
    fstype: nfs4